#!/bin/bash
sudo add-apt-repository ppa:danielrichter2007/grub-customizer &&
sudo apt-get update &&
sudo apt-get install grub-customizer &&
sudo cp -r themes_mint/themes /boot/grub/ &&
sudo grub-customizer
